### ISSUE TITLE
unable to see the counts on the dashboard

### ISSUE THREAD

**Issue by lchunleo** [xe-nvdk/crowd-counting#2]
Hi 

 I have slightly a different setup to point to the influx bucket on my machine. i saw the counts coming in using the data explorer. However, i have issues trying to plot it. Apparently, my y axis does not show the "_value" field though i can see that in the "raw data" table, the _value is populated with counts for every seconds. Can you give some clue or tips how to resolve this as am new to influx db? thank you

**Comment by xe-nvdk** [comment]
Hey, have you figured out how to do it?
